BB=0
#Gramatica de funciones
FN=1
ARGS=2
PL=3
Z=4
RT=5
#Llamada de funciones
B2=6
R=7
ARGS2=8
PL2=9
Z2=10
#Bloque de codigo
AA=11
B=12
#Declaracion y asignacion de variables
D=13
Q=14
L=15
LP=16
Ass=17
#Operaciones matematicas
E=18
EP=19
T=20
TP=21
F=22
F2=23
#Gramatica del bloque IF
I=24
E2=25
Tif=26
#Gramatica para condiciones
Cond=27
Op=28
Ol=29
#Gramatica para bloque While
W=30
C=31
C2=32
G=33

tabla2 = [[BB, 'identificador', None ],
         [BB, 'LPAREN', None ],
         [BB, 'RPAREN', None ],
         [BB, 'coma', None ],
         [BB, 'char', [FN,BB]],
         [BB, 'int', [FN,BB]],
         [BB, 'string', [FN,BB]],
         [BB, 'float', [FN,BB]],
         [BB, 'void', [FN,BB]],
         [BB, 'finInstruccion', None],
         [BB, 'return', None],
         [BB, 'equals', None],
         [BB, 'PLUS', None],
         [BB, 'MINUS', None],
         [BB, 'TIMES', None],
         [BB, 'DIVIDE', None],
         [BB, 'NUMBER', None],
         [BB, 'word', None],
         [BB, 'letter', None],
         [BB, 'equalscomparision', None],
         [BB, 'menorque', None],
         [BB, 'mayorque', None],
         [BB, 'if', None],
         [BB, 'inicioBloque', None],
         [BB, 'finBloque', None],
         [BB, 'else', None],
         [BB, 'while', None],
         [BB, 'eof', ['vacia']],
         [BB, 'not', None],
         [BB, 'and', None],
         [BB, 'OR', None],
         #FN
         [FN, 'identificador', None ],
         [FN, 'LPAREN', None ],
         [FN, 'RPAREN', None ],
         [FN, 'coma', None ],
         [FN, 'char', [RT,'identificador','LPAREN', ARGS, 'RPAREN', B2]],
         [FN, 'int', [RT,'identificador','LPAREN', ARGS, 'RPAREN', B2]],
         [FN, 'string', [RT,'identificador','LPAREN', ARGS, 'RPAREN', B2]],
         [FN, 'float', [RT,'identificador','LPAREN', ARGS, 'RPAREN', B2]],
         [FN, 'void', [RT,'identificador','LPAREN', ARGS, 'RPAREN', B2]],
         [FN, 'finInstruccion', None],
         [FN, 'return', None],
         [FN, 'equals', None],
         [FN, 'PLUS', None],
         [FN, 'MINUS', None],
         [FN, 'TIMES', None],
         [FN, 'DIVIDE', None],
         [FN, 'NUMBER', None],
         [FN, 'word', None],
         [FN, 'letter', None],
         [FN, 'equalscomparision', None],
         [FN, 'menorque', None],
         [FN, 'mayorque', None],
         [FN, 'if', None],
         [FN, 'inicioBloque', None],
         [FN, 'finBloque', None],
         [FN, 'else', None],
         [FN, 'while', None],
         [FN, 'eof', None],
         [FN, 'not', None],
         [FN, 'and', None],
         [FN, 'OR', None],
         #ARGS
         [ARGS, 'identificador', None ],
         [ARGS, 'LPAREN', None ],
         [ARGS, 'RPAREN', ['vacia']],
         [ARGS, 'coma', None ],
         [ARGS, 'char', [PL]],
         [ARGS, 'int', [PL]],
         [ARGS, 'string', [PL]],
         [ARGS, 'float', [PL]],
         [ARGS, 'void', [PL]],
         [ARGS, 'finInstruccion', None],
         [ARGS, 'return', None],
         [ARGS, 'equals', None],
         [ARGS, 'PLUS', None],
         [ARGS, 'MINUS', None],
         [ARGS, 'TIMES', None],
         [ARGS, 'DIVIDE', None],
         [ARGS, 'NUMBER', None],
         [ARGS, 'word', None],
         [ARGS, 'letter', None],
         [ARGS, 'equalscomparision', None],
         [ARGS, 'menorque', None],
         [ARGS, 'mayorque', None],
         [ARGS, 'if', None],
         [ARGS, 'inicioBloque', None],
         [ARGS, 'finBloque', None],
         [ARGS, 'else', None],
         [ARGS, 'while', None],
         [ARGS, 'eof', None],
         [ARGS, 'not', None],
         [ARGS, 'and', None],
         [ARGS, 'OR', None],
         #PL
         [PL, 'identificador', None ],
         [PL, 'LPAREN', None ],
         [PL, 'RPAREN', None ],
         [PL, 'coma', None ],
         [PL, 'char', [RT, 'identificador', Z]],
         [PL, 'int', [RT, 'identificador', Z]],
         [PL, 'string', [RT, 'identificador', Z]],
         [PL, 'float', [RT, 'identificador', Z]],
         [PL, 'void', [RT, 'identificador', Z]],
         [PL, 'finInstruccion', None],
         [PL, 'return', None],
         [PL, 'equals', None],
         [PL, 'PLUS', None],
         [PL, 'MINUS', None],
         [PL, 'TIMES', None],
         [PL, 'DIVIDE', None],
         [PL, 'NUMBER', None],
         [PL, 'word', None],
         [PL, 'letter', None],
         [PL, 'equalscomparision', None],
         [PL, 'menorque', None],
         [PL, 'mayorque', None],
         [PL, 'if', None],
         [PL, 'inicioBloque', None],
         [PL, 'finBloque', None],
         [PL, 'else', None],
         [PL, 'while', None],
         [PL, 'eof', None],
         [PL, 'not', None],
         [PL, 'and', None],
         [PL, 'OR', None],
         #Z
         [Z, 'identificador', None ],
         [Z, 'LPAREN', None ],
         [Z, 'RPAREN', ['vacia']],
         [Z, 'coma', ['coma', PL]],
         [Z, 'char', None],
         [Z, 'int', None],
         [Z, 'string', None],
         [Z, 'float', None],
         [Z, 'void', None],
         [Z, 'finInstruccion', None],
         [Z, 'return', None],
         [Z, 'equals', None],
         [Z, 'PLUS', None],
         [Z, 'MINUS', None],
         [Z, 'TIMES', None],
         [Z, 'DIVIDE', None],
         [Z, 'NUMBER', None],
         [Z, 'word', None],
         [Z, 'letter', None],
         [Z, 'equalscomparision', None],
         [Z, 'menorque', None],
         [Z, 'mayorque', None],
         [Z, 'if', None],
         [Z, 'inicioBloque', None],
         [Z, 'finBloque', None],
         [Z, 'else', None],
         [Z, 'while', None],
         [Z, 'eof', None],
         [Z, 'not', None],
         [Z, 'and', None],
         [Z, 'OR', None],
         #AA
         [AA, 'identificador', [D,AA]],
         [AA, 'LPAREN', None ],
         [AA, 'RPAREN', None ],
         [AA, 'coma', None ],
         [AA, 'char', [D,AA]],
         [AA, 'int', [D,AA]],
         [AA, 'string', [D,AA]],
         [AA, 'float', [D,AA]],
         [AA, 'void', [D,AA]],
         [AA, 'finInstruccion', None],
         [AA, 'return', ['vacia']],
         [AA, 'equals', None],
         [AA, 'PLUS', None],
         [AA, 'MINUS', None],
         [AA, 'TIMES', None],
         [AA, 'DIVIDE', None],
         [AA, 'NUMBER', None],
         [AA, 'word', None],
         [AA, 'letter', None],
         [AA, 'equalscomparision', None],
         [AA, 'menorque', None],
         [AA, 'mayorque', None],
         [AA, 'if', [I,AA]],
         [AA, 'inicioBloque', None],
         [AA, 'finBloque', ['vacia']],
         [AA, 'else', None],
         [AA, 'while', [W,AA]],
         [AA, 'eof', None],
         [AA, 'not', None],
         [AA, 'and', None],
         [AA, 'OR', None],
         #RT
         [RT, 'identificador', None ],
         [RT, 'LPAREN', None ],
         [RT, 'RPAREN', None ],
         [RT, 'coma', None ],
         [RT, 'char', ['char']],
         [RT, 'int', ['int']],
         [RT, 'string', ['string']],
         [RT, 'float', ['float']],
         [RT, 'void', ['void']],
         [RT, 'finInstruccion', None],
         [RT, 'return', None],
         [RT, 'equals', None],
         [RT, 'PLUS', None],
         [RT, 'MINUS', None],
         [RT, 'TIMES', None],
         [RT, 'DIVIDE', None],
         [RT, 'NUMBER', None],
         [RT, 'word', None],
         [RT, 'letter', None],
         [RT, 'equalscomparision', None],
         [RT, 'menorque', None],
         [RT, 'mayorque', None],
         [RT, 'if', None],
         [RT, 'inicioBloque', None],
         [RT, 'finBloque', None],
         [RT, 'else', None],
         [RT, 'while', None],
         [RT, 'eof', None],
         [RT, 'not', None],
         [RT, 'and', None],
         [RT, 'OR', None],
         #B2
         [B2, 'identificador', None ],
         [B2, 'LPAREN', None ],
         [B2, 'RPAREN', None ],
         [B2, 'coma', None ],
         [B2, 'char', None],
         [B2, 'int', None],
         [B2, 'string', None],
         [B2, 'float', None],
         [B2, 'void', None],
         [B2, 'finInstruccion', ['finInstruccion']],
         [B2, 'return', None],
         [B2, 'equals', None],
         [B2, 'PLUS', None],
         [B2, 'MINUS', None],
         [B2, 'TIMES', None],
         [B2, 'DIVIDE', None],
         [B2, 'NUMBER', None],
         [B2, 'word', None],
         [B2, 'letter', None],
         [B2, 'equalscomparision', None],
         [B2, 'menorque', None],
         [B2, 'mayorque', None],
         [B2, 'if', None],
         [B2, 'inicioBloque', ['inicioBloque',AA,R,'finBloque']],
         [B2, 'finBloque', None],
         [B2, 'else', None],
         [B2, 'while', None],
         [B2, 'eof', None],
         [B2, 'not', None],
         [B2, 'and', None],
         [B2, 'OR', None],
         #R
         [R, 'identificador', None ],
         [R, 'LPAREN', None ],
         [R, 'RPAREN', None ],
         [R, 'coma', None ],
         [R, 'char', None],
         [R, 'int', None],
         [R, 'string', None],
         [R, 'float', None],
         [R, 'void', None],
         [R, 'finInstruccion', None],
         [R, 'return', ['return',F,'finInstruccion']],
         [R, 'equals', None],
         [R, 'PLUS', None],
         [R, 'MINUS', None],
         [R, 'TIMES', None],
         [R, 'DIVIDE', None],
         [R, 'NUMBER', None],
         [R, 'word', None],
         [R, 'letter', None],
         [R, 'equalscomparision', None],
         [R, 'menorque', None],
         [R, 'mayorque', None],
         [R, 'if', None],
         [R, 'inicioBloque', None],
         [R, 'finBloque', ['vacia']],
         [R, 'else', None],
         [R, 'while', None],
         [R, 'eof', None],
         [R, 'not', None],
         [R, 'and', None],
         [R, 'OR', None],
         #ARGS2
         [ARGS2, 'identificador', [PL2]],
         [ARGS2, 'LPAREN', None ],
         [ARGS2, 'RPAREN', ['vacia']],
         [ARGS2, 'coma', None ],
         [ARGS2, 'char', None],
         [ARGS2, 'int', None],
         [ARGS2, 'string', None],
         [ARGS2, 'float', None],
         [ARGS2, 'void', None],
         [ARGS2, 'finInstruccion', None],
         [ARGS2, 'return', None],
         [ARGS2, 'equals', None],
         [ARGS2, 'PLUS', None],
         [ARGS2, 'MINUS', None],
         [ARGS2, 'TIMES', None],
         [ARGS2, 'DIVIDE', None],
         [ARGS2, 'NUMBER', [PL2]],
         [ARGS2, 'word', [PL2]],
         [ARGS2, 'letter', [PL2]],
         [ARGS2, 'equalscomparision', None],
         [ARGS2, 'menorque', None],
         [ARGS2, 'mayorque', None],
         [ARGS2, 'if', None],
         [ARGS2, 'inicioBloque', None],
         [ARGS2, 'finBloque', None],
         [ARGS2, 'else', None],
         [ARGS2, 'while', None],
         [ARGS2, 'eof', None],
         [ARGS2, 'not', None],
         [ARGS2, 'and', None],
         [ARGS2, 'OR', None],
         #PL2
         [PL2, 'identificador', [Ass,Z2]],
         [PL2, 'LPAREN', None ],
         [PL2, 'RPAREN', None],
         [PL2, 'coma', None ],
         [PL2, 'char', None],
         [PL2, 'int', None],
         [PL2, 'string', None],
         [PL2, 'float', None],
         [PL2, 'void', None],
         [PL2, 'finInstruccion', None],
         [PL2, 'return', None],
         [PL2, 'equals', None],
         [PL2, 'PLUS', None],
         [PL2, 'MINUS', None],
         [PL2, 'TIMES', None],
         [PL2, 'DIVIDE', None],
         [PL2, 'NUMBER', [Ass,Z2]],
         [PL2, 'word', [Ass,Z2]],
         [PL2, 'letter', [Ass,Z2]],
         [PL2, 'equalscomparision', None],
         [PL2, 'menorque', None],
         [PL2, 'mayorque', None],
         [PL2, 'if', None],
         [PL2, 'inicioBloque', None],
         [PL2, 'finBloque', None],
         [PL2, 'else', None],
         [PL2, 'while', None],
         [PL2, 'eof', None],
         [PL2, 'not', None],
         [PL2, 'and', None],
         [PL2, 'OR', None],
         #Z2
         [Z2, 'identificador', None],
         [Z2, 'LPAREN', None ],
         [Z2, 'RPAREN', ['vacia']],
         [Z2, 'coma', ['coma',PL2]],
         [Z2, 'char', None],
         [Z2, 'int', None],
         [Z2, 'string', None],
         [Z2, 'float', None],
         [Z2, 'void', None],
         [Z2, 'finInstruccion', None],
         [Z2, 'return', None],
         [Z2, 'equals', None],
         [Z2, 'PLUS', None],
         [Z2, 'MINUS', None],
         [Z2, 'TIMES', None],
         [Z2, 'DIVIDE', None],
         [Z2, 'NUMBER', None],
         [Z2, 'word', None],
         [Z2, 'letter', None],
         [Z2, 'equalscomparision', None],
         [Z2, 'menorque', None],
         [Z2, 'mayorque', None],
         [Z2, 'if', None],
         [Z2, 'inicioBloque', None],
         [Z2, 'finBloque', None],
         [Z2, 'else', None],
         [Z2, 'while', None],
         [Z2, 'eof', None],
         [Z2, 'not', None],
         [Z2, 'and', None],
         [Z2, 'OR', None],
         #D
         [D, 'identificador', ['identificador',Q]],
         [D, 'LPAREN', None ],
         [D, 'RPAREN', None],
         [D, 'coma', None],
         [D, 'char', [RT,'identificador',LP]],
         [D, 'int', [RT,'identificador',LP]],
         [D, 'string', [RT,'identificador',LP]],
         [D, 'float', [RT,'identificador',LP]],
         [D, 'void', [RT,'identificador',LP]],
         [D, 'finInstruccion', None],
         [D, 'return', None],
         [D, 'equals', None],
         [D, 'PLUS', None],
         [D, 'MINUS', None],
         [D, 'TIMES', None],
         [D, 'DIVIDE', None],
         [D, 'NUMBER', None],
         [D, 'word', None],
         [D, 'letter', None],
         [D, 'equalscomparision', None],
         [D, 'menorque', None],
         [D, 'mayorque', None],
         [D, 'if', None],
         [D, 'inicioBloque', None],
         [D, 'finBloque', None],
         [D, 'else', None],
         [D, 'while', None],
         [D, 'eof', None],
         [D, 'not', None],
         [D, 'and', None],
         [D, 'OR', None],
         #Q
         [Q, 'identificador', None],
         [Q, 'LPAREN', ['LPAREN',ARGS2,'RPAREN','finInstruccion']],
         [Q, 'RPAREN', None],
         [Q, 'coma', None],
         [Q, 'char', None],
         [Q, 'int', None],
         [Q, 'string', None],
         [Q, 'float', None],
         [Q, 'void', None],
         [Q, 'finInstruccion', None],
         [Q, 'return', None],
         [Q, 'equals', ['equals',Ass,'finInstruccion']],
         [Q, 'PLUS', None],
         [Q, 'MINUS', None],
         [Q, 'TIMES', None],
         [Q, 'DIVIDE', None],
         [Q, 'NUMBER', None],
         [Q, 'word', None],
         [Q, 'letter', None],
         [Q, 'equalscomparision', None],
         [Q, 'menorque', None],
         [Q, 'mayorque', None],
         [Q, 'if', None],
         [Q, 'inicioBloque', None],
         [Q, 'finBloque', None],
         [Q, 'else', None],
         [Q, 'while', None],
         [Q, 'eof', None],
         [Q, 'not', None],
         [Q, 'and', None],
         [Q, 'OR', None],
         #L
         [L, 'identificador', None],
         [L, 'LPAREN', None],
         [L, 'RPAREN', None],
         [L, 'coma', ['coma','identificador',LP]],
         [L, 'char', None],
         [L, 'int', None],
         [L, 'string', None],
         [L, 'float', None],
         [L, 'void', None],
         [L, 'finInstruccion', ['finInstruccion']],
         [L, 'return', None],
         [L, 'equals', None],
         [L, 'PLUS', None],
         [L, 'MINUS', None],
         [L, 'TIMES', None],
         [L, 'DIVIDE', None],
         [L, 'NUMBER', None],
         [L, 'word', None],
         [L, 'letter', None],
         [L, 'equalscomparision', None],
         [L, 'menorque', None],
         [L, 'mayorque', None],
         [L, 'if', None],
         [L, 'inicioBloque', None],
         [L, 'finBloque', None],
         [L, 'else', None],
         [L, 'while', None],
         [L, 'eof', None],
         [L, 'not', None],
         [L, 'and', None],
         [L, 'OR', None],
         #LP
         [LP, 'identificador', None],
         [LP, 'LPAREN', None],
         [LP, 'RPAREN', None],
         [LP, 'coma', [L]],
         [LP, 'char', None],
         [LP, 'int', None],
         [LP, 'string', None],
         [LP, 'float', None],
         [LP, 'void', None],
         [LP, 'finInstruccion', [L]],
         [LP, 'return', None],
         [LP, 'equals', ['equals',Ass,L]],
         [LP, 'PLUS', None],
         [LP, 'MINUS', None],
         [LP, 'TIMES', None],
         [LP, 'DIVIDE', None],
         [LP, 'NUMBER', None],
         [LP, 'word', None],
         [LP, 'letter', None],
         [LP, 'equalscomparision', None],
         [LP, 'menorque', None],
         [LP, 'mayorque', None],
         [LP, 'if', None],
         [LP, 'inicioBloque', None],
         [LP, 'finBloque', None],
         [LP, 'else', None],
         [LP, 'while', None],
         [LP, 'eof', None],
         [LP, 'not', None],
         [LP, 'and', None],
         [LP, 'OR', None],
         #Ass
         [Ass, 'identificador', [E]],
         [Ass, 'LPAREN', [E]],
         [Ass, 'RPAREN', None],
         [Ass, 'coma', None],
         [Ass, 'char', None],
         [Ass, 'int', None],
         [Ass, 'string', None],
         [Ass, 'float', None],
         [Ass, 'void', None],
         [Ass, 'finInstruccion', None],
         [Ass, 'return', None],
         [Ass, 'equals', None],
         [Ass, 'PLUS', None],
         [Ass, 'MINUS', None],
         [Ass, 'TIMES', None],
         [Ass, 'DIVIDE', None],
         [Ass, 'NUMBER', [E]],
         [Ass, 'word', [C]],
         [Ass, 'letter', [C]],
         [Ass, 'equalscomparision', None],
         [Ass, 'menorque', None],
         [Ass, 'mayorque', None],
         [Ass, 'if', None],
         [Ass, 'inicioBloque', None],
         [Ass, 'finBloque', None],
         [Ass, 'else', None],
         [Ass, 'while', None],
         [Ass, 'eof', None],
         [Ass, 'not', None],
         [Ass, 'and', None],
         [Ass, 'OR', None],
         #E
         [E, 'identificador', [T,EP]],
         [E, 'LPAREN', [T,EP]],
         [E, 'RPAREN', None],
         [E, 'coma', None],
         [E, 'char', None],
         [E, 'int', None],
         [E, 'string', None],
         [E, 'float', None],
         [E, 'void', None],
         [E, 'finInstruccion', None],
         [E, 'return', None],
         [E, 'equals', None],
         [E, 'PLUS', None],
         [E, 'MINUS', None],
         [E, 'TIMES', None],
         [E, 'DIVIDE', None],
         [E, 'NUMBER', [T,EP]],
         [E, 'word', [T,EP]],
         [E, 'letter', [T,EP]],
         [E, 'equalscomparision', None],
         [E, 'menorque', None],
         [E, 'mayorque', None],
         [E, 'if', None],
         [E, 'inicioBloque', None],
         [E, 'finBloque', None],
         [E, 'else', None],
         [E, 'while', None],
         [E, 'eof', None],
         [E, 'not', None],
         [E, 'and', None],
         [E, 'OR', None],
         #EP
         [EP, 'identificador', None],
         [EP, 'LPAREN', None],
         [EP, 'RPAREN', ['vacia']],
         [EP, 'coma', ['vacia']],
         [EP, 'char', None],
         [EP, 'int', None],
         [EP, 'string', None],
         [EP, 'float', None],
         [EP, 'void', None],
         [EP, 'finInstruccion', ['vacia']],
         [EP, 'return', None],
         [EP, 'equals', ['vacia']],
         [EP, 'PLUS', ['PLUS',T,EP]],
         [EP, 'MINUS', ['MINUS',T,EP]],
         [EP, 'TIMES', None],
         [EP, 'DIVIDE', None],
         [EP, 'NUMBER', None],
         [EP, 'word', None],
         [EP, 'letter', None],
         [EP, 'equalscomparision', ['vacia']],
         [EP, 'menorque', ['vacia']],
         [EP, 'mayorque', ['vacia']],
         [EP, 'if', None],
         [EP, 'inicioBloque', None],
         [EP, 'finBloque', None],
         [EP, 'else', None],
         [EP, 'while', None],
         [EP, 'eof', None],
         [EP, 'not', ['vacia']],
         [EP, 'and', ['vacia']],
         [EP, 'OR', ['vacia']],
         #T
         [T, 'identificador', [F,TP]],
         [T, 'LPAREN', [F,TP]],
         [T, 'RPAREN', None],
         [T, 'coma', None],
         [T, 'char', None],
         [T, 'int', None],
         [T, 'string', None],
         [T, 'float', None],
         [T, 'void', None],
         [T, 'finInstruccion', None],
         [T, 'return', None],
         [T, 'equals', None],
         [T, 'PLUS', None],
         [T, 'MINUS', None],
         [T, 'TIMES', None],
         [T, 'DIVIDE', None],
         [T, 'NUMBER', [F,TP]],
         [T, 'word', [F,TP]],
         [T, 'letter', [F,TP]],
         [T, 'equalscomparision', None],
         [T, 'menorque', None],
         [T, 'mayorque', None],
         [T, 'if', None],
         [T, 'inicioBloque', None],
         [T, 'finBloque', None],
         [T, 'else', None],
         [T, 'while', None],
         [T, 'eof', None],
         [T, 'not', None],
         [T, 'and', None],
         [T, 'OR', None],
         #TP
         [TP, 'identificador', ['vacia']],
         [TP, 'LPAREN', None],
         [TP, 'RPAREN', ['vacia']],
         [TP, 'coma', ['vacia']],
         [TP, 'char', ['vacia']],
         [TP, 'int', ['vacia']],
         [TP, 'string', ['vacia']],
         [TP, 'float', ['vacia']],
         [TP, 'void', ['vacia']],
         [TP, 'finInstruccion', ['vacia']],
         [TP, 'return', ['vacia']],
         [TP, 'equals', ['vacia']],
         [TP, 'PLUS', ['vacia']],
         [TP, 'MINUS', ['vacia']],
         [TP, 'TIMES', ['TIMES',F,TP]],
         [TP, 'DIVIDE', ['DIVIDE',F,TP]],
         [TP, 'NUMBER', None],
         [TP, 'word', None],
         [TP, 'letter', None],
         [TP, 'equalscomparision', ['vacia']],
         [TP, 'menorque', ['vacia']],
         [TP, 'mayorque', ['vacia']],
         [TP, 'if', ['vacia']],
         [TP, 'inicioBloque', None],
         [TP, 'finBloque', ['vacia']],
         [TP, 'else', None],
         [TP, 'while', ['vacia']],
         [TP, 'eof', None],
         [TP, 'not', ['vacia']],
         [TP, 'and', ['vacia']],
         [TP, 'OR', ['vacia']],
         #F
         [F, 'identificador', ['identificador',F2]],
         [F, 'LPAREN', ['LPAREN',E,'RPAREN']],
         [F, 'RPAREN', None],
         [F, 'coma', None],
         [F, 'char', None],
         [F, 'int', None],
         [F, 'string', None],
         [F, 'float', None],
         [F, 'void', None],
         [F, 'finInstruccion', None],
         [F, 'return', None],
         [F, 'equals', None],
         [F, 'PLUS', None],
         [F, 'MINUS', None],
         [F, 'TIMES', None],
         [F, 'DIVIDE', None],
         [F, 'NUMBER', ['NUMBER']],
         [F, 'word', None],
         [F, 'letter', None],
         [F, 'equalscomparision', None],
         [F, 'menorque', None],
         [F, 'mayorque', None],
         [F, 'if', None],
         [F, 'inicioBloque', None],
         [F, 'finBloque', None],
         [F, 'else', None],
         [F, 'while', None],
         [F, 'eof', None],
         [F, 'not', None],
         [F, 'and', None],
         [F, 'OR', None],
         #F2
         [F2, 'identificador', None],
         [F2, 'LPAREN', ['LPAREN',ARGS2,'RPAREN']],
         [F2, 'RPAREN', ['vacia']],
         [F2, 'coma', ['vacia']],
         [F2, 'char', None],
         [F2, 'int', None],
         [F2, 'string', None],
         [F2, 'float', None],
         [F2, 'void', None],
         [F2, 'finInstruccion', ['vacia']],
         [F2, 'return', None],
         [F2, 'equals', None],
         [F2, 'PLUS', ['vacia']],
         [F2, 'MINUS', ['vacia']],
         [F2, 'TIMES', ['vacia']],
         [F2, 'DIVIDE', ['vacia']],
         [F2, 'NUMBER', None],
         [F2, 'word', None],
         [F2, 'letter', None],
         [F2, 'equalscomparision', ['vacia']],
         [F2, 'menorque', ['vacia']],
         [F2, 'mayorque',['vacia']], 
         [F2, 'if', None],
         [F2, 'inicioBloque', None], 
         [F2, 'finBloque', None],
         [F2, 'else', None],
         [F2, 'while', None],
         [F2, 'eof', ['vacia']],
         [F2, 'not', ['vacia']],
         [F2, 'and', ['vacia']],
         [F2, 'OR',['vacia']],
         #Cond
         [Cond, 'identificador', [E,Op,E,Ol]],
         [Cond, 'LPAREN', [E,Op,E,Ol]],
         [Cond, 'RPAREN', None],
         [Cond, 'coma', None],
         [Cond, 'char', None],
         [Cond, 'int', None],
         [Cond, 'string', None],
         [Cond, 'float', None],
         [Cond, 'void', None],
         [Cond, 'finInstruccion', None],
         [Cond, 'return', None],
         [Cond, 'equals', None],
         [Cond, 'PLUS', None],
         [Cond, 'MINUS', None],
         [Cond, 'TIMES', None],
         [Cond, 'DIVIDE', None],
         [Cond, 'NUMBER', [E,Op,E,Ol]],
         [Cond, 'word', [E,Op,E,Ol]],
         [Cond, 'letter', [E,Op,E,Ol]],
         [Cond, 'equalscomparision', None],
         [Cond, 'menorque', None],
         [Cond, 'mayorque', None],
         [Cond, 'if', None],
         [Cond, 'inicioBloque', None],
         [Cond, 'finBloque', None],
         [Cond, 'else', None],
         [Cond, 'while', None],
         [Cond, 'eof', None],
         [Cond, 'not', None],
         [Cond, 'and', None],
         [Cond, 'OR', None],
         #Op
         [Op, 'identificador', None],
         [Op, 'LPAREN', None],
         [Op, 'RPAREN', None],
         [Op, 'coma', None],
         [Op, 'char', None],
         [Op, 'int', None],
         [Op, 'string', None],
         [Op, 'float', None],
         [Op, 'void', None],
         [Op, 'finInstruccion', None],
         [Op, 'return', None],
         [Op, 'equals', None],
         [Op, 'PLUS', None],
         [Op, 'MINUS', None],
         [Op, 'TIMES', None],
         [Op, 'DIVIDE', None],
         [Op, 'NUMBER', None],
         [Op, 'word', None],
         [Op, 'letter', None],
         [Op, 'equalscomparision', ['equalscomparision']],
         [Op, 'menorque', ['menorque']],
         [Op, 'mayorque', ['mayorque']],
         [Op, 'if', None],
         [Op, 'inicioBloque', None],
         [Op, 'finBloque', None],
         [Op, 'else', None],
         [Op, 'while', None],
         [Op, 'eof', None],
         [Op, 'not', ['not','equals']],
         [Op, 'and', None],
         [Op, 'OR', None],
         #G
         [Ol, 'identificador', None],
         [Ol, 'LPAREN', None],
         [Ol, 'RPAREN', ['vacia']],
         [Ol, 'coma', None],
         [Ol, 'char', None],
         [Ol, 'int', None],
         [Ol, 'strinOl', None],
         [Ol, 'float', None],
         [Ol, 'void', None],
         [Ol, 'finInstruccion', None],
         [Ol, 'return', None],
         [Ol, 'equals', None],
         [Ol, 'PLUS', None],
         [Ol, 'MINUS', None],
         [Ol, 'TIMES', None],
         [Ol, 'DIVIDE', None],
         [Ol, 'NUMBER', None],
         [Ol, 'word', None],
         [Ol, 'letter', None],
         [Ol, 'equalscomparision', None],
         [Ol, 'menorque', None],
         [Ol, 'mayorque', None],
         [Ol, 'if', None],
         [Ol, 'inicioBloque', None],
         [Ol, 'finBloque', None],
         [Ol, 'else', None],
         [Ol, 'while', None],
         [Ol, 'eof', None],
         [Ol, 'not', None],
         [Ol, 'and', ['and',Cond]],
         [Ol, 'OR', ['OR',Cond]],
         #I
         [I, 'identificador', None],
         [I, 'LPAREN', None],
         [I, 'RPAREN', None],
         [I, 'coma', None],
         [I, 'char', None],
         [I, 'int', None],
         [I, 'string', None],
         [I, 'float', None],
         [I, 'void', None],
         [I, 'finInstruccion', None],
         [I, 'return', None],
         [I, 'equals', None],
         [I, 'PLUS', None],
         [I, 'MINUS', None],
         [I, 'TIMES', None],
         [I, 'DIVIDE', None],
         [I, 'NUMBER', None],
         [I, 'word', None],
         [I, 'letter', None],
         [I, 'equalscomparision', None],
         [I, 'menorque', None],
         [I, 'mayorque', None],
         [I, 'if', ['if','LPAREN',Cond,'RPAREN',B,E2]],
         [I, 'inicioBloque', None],
         [I, 'finBloque', None],
         [I, 'else', None],
         [I, 'while', None],
         [I, 'eof', None],
         [I, 'not', None],
         [I, 'and', None],
         [I, 'OR', None],
         #B
         [B, 'identificador', None],
         [B, 'LPAREN', None],
         [B, 'RPAREN', None],
         [B, 'coma', None],
         [B, 'char', None],
         [B, 'int', None],
         [B, 'string', None],
         [B, 'float', None],
         [B, 'void', None],
         [B, 'finInstruccion', None],
         [B, 'return', None],
         [B, 'equals', None],
         [B, 'PLUS', None],
         [B, 'MINUS', None],
         [B, 'TIMES', None],
         [B, 'DIVIDE', None],
         [B, 'NUMBER', None],
         [B, 'word', None],
         [B, 'letter', None],
         [B, 'equalscomparision', None],
         [B, 'menorque', None],
         [B, 'mayorque', None],
         [B, 'if', None],
         [B, 'inicioBloque', ['inicioBloque',AA,R,'finBloque']],
         [B, 'finBloque', None],
         [B, 'else', None],
         [B, 'while', None],
         [B, 'eof', None],
         [B, 'not', None],
         [B, 'and', None],
         [B, 'OR', None],
         #E2
         [E2, 'identificador', ['vacia']],
         [E2, 'LPAREN', None],
         [E2, 'RPAREN', None],
         [E2, 'coma', None],
         [E2, 'char', ['vacia']],
         [E2, 'int', ['vacia']],
         [E2, 'string', ['vacia']],
         [E2, 'float', ['vacia']],
         [E2, 'void', ['vacia']],
         [E2, 'finInstruccion', None],
         [E2, 'return', ['vacia']],
         [E2, 'equals', None],
         [E2, 'PLUS', None],
         [E2, 'MINUS', None],
         [E2, 'TIMES', None],
         [E2, 'DIVIDE', None],
         [E2, 'NUMBER', None],
         [E2, 'word', None],
         [E2, 'letter', None],
         [E2, 'equalscomparision', None],
         [E2, 'menorque', None],
         [E2, 'mayorque', None],
         [E2, 'if', ['vacia']],
         [E2, 'inicioBloque', None],
         [E2, 'finBloque', ['vacia']],
         [E2, 'else', ['else',Tif]],
         [E2, 'while', ['vacia']],
         [E2, 'eof', None],
         [E2, 'not', None],
         [E2, 'and', None],
         [E2, 'OR', None],
         #Tif
         [Tif, 'identificador', None],
         [Tif, 'LPAREN', None],
         [Tif, 'RPAREN', None],
         [Tif, 'coma', None],
         [Tif, 'char', None],
         [Tif, 'int', None],
         [Tif, 'string', None],
         [Tif, 'float', None],
         [Tif, 'void', None],
         [Tif, 'finInstruccion', None],
         [Tif, 'return', None],
         [Tif, 'equals', None],
         [Tif, 'PLUS', None],
         [Tif, 'MINUS', None],
         [Tif, 'TIMES', None],
         [Tif, 'DIVIDE', None],
         [Tif, 'NUMBER', None],
         [Tif, 'word', None],
         [Tif, 'letter', None],
         [Tif, 'equalscomparision', None],
         [Tif, 'menorque', None],
         [Tif, 'mayorque', None],
         [Tif, 'if', [I]],
         [Tif, 'inicioBloque', [B]],
         [Tif, 'finBloque', None],
         [Tif, 'else', None],
         [Tif, 'while', None],
         [Tif, 'eof', None],
         [Tif, 'not', None],
         [Tif, 'and', None],
         [Tif, 'OR', None],
         #W
         [W, 'identificador', None],
         [W, 'LPAREN', None],
         [W, 'RPAREN', None],
         [W, 'coma', None],
         [W, 'char', None],
         [W, 'int', None],
         [W, 'string', None],
         [W, 'float', None],
         [W, 'void', None],
         [W, 'finInstruccion', None],
         [W, 'return', None],
         [W, 'equals', None],
         [W, 'PLUS', None],
         [W, 'MINUS', None],
         [W, 'TIMES', None],
         [W, 'DIVIDE', None],
         [W, 'NUMBER', None],
         [W, 'word', None],
         [W, 'letter', None],
         [W, 'equalscomparision', None],
         [W, 'menorque', None],
         [W, 'mayorque', None],
         [W, 'if', None],
         [W, 'inicioBloque', None],
         [W, 'finBloque', None],
         [W, 'else', None],
         [W, 'while', ['while','LPAREN',Cond,'RPAREN',B]],
         [W, 'eof', None],
         [W, 'not', None],
         [W, 'and', None],
         [W, 'OR', None],
         # TODO: C, C3, G
         #C
         [C, 'identificador', None],
         [C, 'LPAREN', None],
         [C, 'RPAREN', None],
         [C, 'coma', None],
         [C, 'char', None],
         [C, 'int', None],
         [C, 'string', None],
         [C, 'float', None],
         [C, 'void', None],
         [C, 'finInstruccion', None],
         [C, 'return', None],
         [C, 'equals', None],
         [C, 'PLUS', None],
         [C, 'MINUS', None],
         [C, 'TIMES', None],
         [C, 'DIVIDE', None],
         [C, 'NUMBER', None],
         [C, 'word', [G,C2]],
         [C, 'letter', [G,C2]],
         [C, 'equalscomparision', None],
         [C, 'menorque', None],
         [C, 'mayorque', None],
         [C, 'if', None],
         [C, 'inicioBloque', None],
         [C, 'finBloque', None],
         [C, 'else', None],
         [C, 'while', ['while','LPAREN',Cond,'RPAREN',B]],
         [C, 'eof', None],
         [C, 'not', None],
         [C, 'and', None],
         [C, 'OR', None],
         #C2
         [C2, 'identificador', None],
         [C2, 'LPAREN', None],
         [C2, 'RPAREN', ['vacia']],
         [C2, 'coma', ['vacia']],
         [C2, 'char', None],
         [C2, 'int', None],
         [C2, 'string', None],
         [C2, 'float', None],
         [C2, 'void', None],
         [C2, 'finInstruccion',['vacia']],
         [C2, 'return', None],
         [C2, 'equals', None],
         [C2, 'PLUS', ['PLUS',G,C2]],
         [C2, 'MINUS', None],
         [C2, 'TIMES', None],
         [C2, 'DIVIDE', None],
         [C2, 'NUMBER', None],
         [C2, 'word', None],
         [C2, 'letter', None],
         [C2, 'equalscomparision', None],
         [C2, 'menorque', None],
         [C2, 'mayorque', None],
         [C2, 'if', None],
         [C2, 'inicioBloque', None],
         [C2, 'finBloque', None],
         [C2, 'else', None],
         [C2, 'while', ['while','LPAREN',Cond,'RPAREN',B]],
         [C2, 'eof', None],
         [C2, 'not', None],
         [C2, 'and', None],
         [C2, 'OR', None],
         #G
         [G, 'identificador', None],
         [G, 'LPAREN', None],
         [G, 'RPAREN', None],
         [G, 'coma', None],
         [G, 'char', None],
         [G, 'int', None],
         [G, 'string', None],
         [G, 'float', None],
         [G, 'void', None],
         [G, 'finInstruccion', None],
         [G, 'return', None],
         [G, 'equals', None],
         [G, 'PLUS', None],
         [G, 'MINUS', None],
         [G, 'TIMES', None],
         [G, 'DIVIDE', None],
         [G, 'NUMBER', None],
         [G, 'word', ['word']],
         [G, 'letter', ['letter']],
         [G, 'equalscomparision', None],
         [G, 'menorque', None],
         [G, 'mayorque', None],
         [G, 'if', None],
         [G, 'inicioBloque', None],
         [G, 'finBloque', None],
         [G, 'else', None],
         [G, 'while', ['while','LPAREN',Cond,'RPAREN',B]],
         [G, 'eof', None],
         [G, 'not', None],
         [G, 'and', None],
         [G, 'OR', None],
         ]
